from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QApplication, QLabel,  QTableWidget,QHBoxLayout, QTableWidgetItem, QComboBox,QFrame
from PyQt5.QtCore import Qt
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1272, 796)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font2 = QtGui.QFont()
        font2.setFamily("Arial")
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setWeight(75)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1252, 786))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label1 = QtWidgets.QLabel(self.tab)
        self.label1.setGeometry(QtCore.QRect(960, 50, 260, 400))
        self.label1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label1.setText("")
        self.label1.setPixmap(QtGui.QPixmap("aoi.jpg"))
        self.label1.setScaledContents(True)
        self.label1.setObjectName("label_Image")
        self.Textlabel = QtWidgets.QLabel(self.tab)
        self.Textlabel.setGeometry(QtCore.QRect(10, 600, 900, 100))
        self.Textlabel.setFont(font)
        self.Textlabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Textlabel.setText("")
        self.Textlabel.setPixmap(QtGui.QPixmap("aoi.jpg"))
        self.Textlabel.setScaledContents(True)
        self.Textlabel.setObjectName("label_Image")
        self.Textlabel.setWordWrap(True)
        self.label_Image = QtWidgets.QLabel(self.tab)
        self.label_Image.setGeometry(QtCore.QRect(10, 50, 900, 500))
        self.label_Image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_Image.setText("")
        self.label_Image.setPixmap(QtGui.QPixmap("aoi.jpg"))
        self.label_Image.setScaledContents(False)
        self.label_Image.setObjectName("label_Image")
        
        self.toolButton_Load_Image = QtWidgets.QToolButton(self.tab)
        self.toolButton_Load_Image.setGeometry(QtCore.QRect(980, 60, 220, 80))
        self.toolButton_Load_Image.setFont(font)
        self.toolButton_Load_Image.setObjectName("toolButton_Load_Image")
        self.toolButton_Identify_Image = QtWidgets.QToolButton(self.tab)
        self.toolButton_Identify_Image.setGeometry(QtCore.QRect(980, 160, 220, 80))
        self.toolButton_Identify_Image.setFont(font)
        self.toolButton_Identify_Image.setObjectName("toolButton_Identify_Image")
        self.toolButton_Delete_Image = QtWidgets.QToolButton(self.tab)
        self.toolButton_Delete_Image.setGeometry(QtCore.QRect(980, 260, 220, 80))
        self.toolButton_Delete_Image.setFont(font)
        self.toolButton_Delete_Image.setObjectName("toolButton_Load_Image")
        self.toolButton_Catch = QtWidgets.QToolButton(self.tab)
        self.toolButton_Catch.setGeometry(QtCore.QRect(980, 360, 220, 80))
        self.toolButton_Catch.setFont(font)
        self.toolButton_Catch.setObjectName("toolButton_Load_Image")

        self.tabWidget.addTab(self.tab, "")

        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.label2 = QtWidgets.QLabel(self.tab2)
        self.label2.setFont(font2)
        self.label2.setGeometry(QtCore.QRect(10, 100, 1190, 500))
        self.label2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label2.setText("")
        self.label2.setPixmap(QtGui.QPixmap("aoi.jpg"))
        self.label2.setScaledContents(True)
        self.label2.setObjectName("Text2")

        self.tabWidget.addTab(self.tab2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1272, 25))
        self.menubar.setObjectName("menubar")
##        self.menuFile = QtWidgets.QMenu(self.menubar)
##        self.menuFile.setObjectName("menuFile")
        self.menuAnalysis = QtWidgets.QMenu(self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
##        self.menuConvolution = QtWidgets.QMenu(self.menubar)
##        self.menuConvolution.setObjectName("menuConvolution")
##        self.menuMorphology = QtWidgets.QMenu(self.menubar)
##        self.menuMorphology.setObjectName("menuMorphology")
##        self.menuHelp = QtWidgets.QMenu(self.menubar)
##        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
##        self.actionLoad_Image = QtWidgets.QAction(MainWindow)
##        self.actionLoad_Image.setObjectName("actionLoad_Image")
##        self.actionSave_Image = QtWidgets.QAction(MainWindow)
##        self.actionSave_Image.setObjectName("actionSave_Image")
##        self.action = QtWidgets.QAction(MainWindow)
##        self.action.setObjectName("action")
        self.actionAFigure = QtWidgets.QAction(MainWindow)
        self.actionAFigure.setObjectName("Accuracy figure")
        self.actionLFigure = QtWidgets.QAction(MainWindow)
        self.actionLFigure.setObjectName("Loss figure")
##        self.menuFile.addAction(self.actionLoad_Image)
##        self.menuFile.addAction(self.actionSave_Image)
##        self.menuFile.addSeparator()
##        self.menuFile.addAction(self.action)
        self.menuAnalysis.addAction(self.actionAFigure)
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.actionLFigure)
##        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
##        self.menubar.addAction(self.menuConvolution.menuAction())
##        self.menubar.addAction(self.menuMorphology.menuAction())
##        self.menubar.addAction(self.menuHelp.menuAction())
        
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "iVi Lab -- Taipei Tech"))
        self.toolButton_Load_Image.setText(_translate("MainWindow", "Load Image"))
        self.toolButton_Identify_Image.setText(_translate("MainWindow", "Identify Image"))
        self.toolButton_Delete_Image.setText(_translate("MainWindow", "Delete Image"))
        self.toolButton_Catch.setText(_translate("MainWindow", "Get Information"))
##        self.toolButton2_Load_Image.setText(_translate("MainWindow", "Load Image"))
##        self.toolButton2_Identify_Image.setText(_translate("MainWindow", "Identify Image"))
##        self.toolButton2_Delete_Image.setText(_translate("MainWindow", "Delete Image"))
##        self.toolButton2_Translate_Image.setText(_translate("MainWindow", "Translate Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Loading"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Information"))
##        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis"))
##        self.menuConvolution.setTitle(_translate("MainWindow", "Convolution"))
##        self.menuMorphology.setTitle(_translate("MainWindow", "Morphology"))
##        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
##        self.actionLoad_Image.setText(_translate("MainWindow", "Load Image"))
##        self.actionSave_Image.setText(_translate("MainWindow", "Save Image"))
##        self.action.setText(_translate("MainWindow", "--"))
        self.actionAFigure.setText(_translate("MainWindow", "Accuracy figure"))
        self.actionLFigure.setText(_translate("MainWindow", "Loss figure"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
